
using Fliq.Domain.Entities.Event;

namespace Fliq.Infrastructure.Persistence
{
    public static class CurrencySeeder
    {
        public static void Seed(FliqDbContext context)
        {
            if (!context.Currencies.Any())
            {
                var currencies = new List<Currency>
            {
                new Currency { CurrencyCode = "USD", Name = "US Dollar", CountryCode = "US" },
                    new Currency { CurrencyCode = "EUR", Name = "Euro", CountryCode = "EU" },
                    new Currency { CurrencyCode = "GBP", Name = "British Pound", CountryCode = "GB" },
                    new Currency { CurrencyCode = "JPY", Name = "Japanese Yen", CountryCode = "JP" },
                    new Currency { CurrencyCode = "CNY", Name = "Chinese Yuan", CountryCode = "CN" },
                    new Currency { CurrencyCode = "AUD", Name = "Australian Dollar", CountryCode = "AU" },
                    new Currency { CurrencyCode = "CAD", Name = "Canadian Dollar", CountryCode = "CA" },
                    new Currency { CurrencyCode = "CHF", Name = "Swiss Franc", CountryCode = "CH" },
                    new Currency { CurrencyCode = "HKD", Name = "Hong Kong Dollar", CountryCode = "HK" },
                    new Currency { CurrencyCode = "SGD", Name = "Singapore Dollar", CountryCode = "SG" },
                    new Currency { CurrencyCode = "SEK", Name = "Swedish Krona", CountryCode = "SE" },
                    new Currency { CurrencyCode = "KRW", Name = "South Korean Won", CountryCode = "KR" },
                    new Currency { CurrencyCode = "NOK", Name = "Norwegian Krone", CountryCode = "NO" },
                    new Currency { CurrencyCode = "NZD", Name = "New Zealand Dollar", CountryCode = "NZ" },
                    new Currency { CurrencyCode = "INR", Name = "Indian Rupee", CountryCode = "IN" },
                    new Currency { CurrencyCode = "RUB", Name = "Russian Ruble", CountryCode = "RU" },
                    new Currency { CurrencyCode = "BRL", Name = "Brazilian Real", CountryCode = "BR" },
                    new Currency { CurrencyCode = "ZAR", Name = "South African Rand", CountryCode = "ZA" },
                    new Currency { CurrencyCode = "MXN", Name = "Mexican Peso", CountryCode = "MX" },
                    new Currency { CurrencyCode = "AED", Name = "United Arab Emirates Dirham", CountryCode = "AE" },
                    new Currency { CurrencyCode = "THB", Name = "Thai Baht", CountryCode = "TH" },
                    new Currency { CurrencyCode = "TRY", Name = "Turkish Lira", CountryCode = "TR" },
                    new Currency { CurrencyCode = "PLN", Name = "Polish Złoty", CountryCode = "PL" },
                    new Currency { CurrencyCode = "IDR", Name = "Indonesian Rupiah", CountryCode = "ID" },
                    new Currency { CurrencyCode = "HUF", Name = "Hungarian Forint", CountryCode = "HU" },
                    new Currency { CurrencyCode = "CZK", Name = "Czech Koruna", CountryCode = "CZ" },
                    new Currency { CurrencyCode = "ILS", Name = "Israeli New Shekel", CountryCode = "IL" },
                    new Currency { CurrencyCode = "CLP", Name = "Chilean Peso", CountryCode = "CL" },
                    new Currency { CurrencyCode = "PHP", Name = "Philippine Peso", CountryCode = "PH" },
                    new Currency { CurrencyCode = "ARS", Name = "Argentine Peso", CountryCode = "AR" },
                    new Currency { CurrencyCode = "MYR", Name = "Malaysian Ringgit", CountryCode = "MY" },
                    new Currency { CurrencyCode = "COP", Name = "Colombian Peso", CountryCode = "CO" },
                    new Currency { CurrencyCode = "NGN", Name = "Nigerian Naira", CountryCode = "NG" },
                    new Currency { CurrencyCode = "PKR", Name = "Pakistani Rupee", CountryCode = "PK" },
                    new Currency { CurrencyCode = "EGP", Name = "Egyptian Pound", CountryCode = "EG" },
                    new Currency { CurrencyCode = "RON", Name = "Romanian Leu", CountryCode = "RO" },
                    new Currency { CurrencyCode = "QAR", Name = "Qatari Riyal", CountryCode = "QA" },
                    new Currency { CurrencyCode = "SAR", Name = "Saudi Riyal", CountryCode = "SA" },
                    new Currency { CurrencyCode = "UAH", Name = "Ukrainian Hryvnia", CountryCode = "UA" },
                    new Currency { CurrencyCode = "VND", Name = "Vietnamese Đồng", CountryCode = "VN" },
                    new Currency { CurrencyCode = "BDT", Name = "Bangladeshi Taka", CountryCode = "BD" },
                    new Currency { CurrencyCode = "KWD", Name = "Kuwaiti Dinar", CountryCode = "KW" },
                    new Currency { CurrencyCode = "DKK", Name = "Danish Krone", CountryCode = "DK" },
                    new Currency { CurrencyCode = "PEN", Name = "Peruvian Sol", CountryCode = "PE" },
                    new Currency { CurrencyCode = "TWD", Name = "New Taiwan Dollar", CountryCode = "TW" },
                    new Currency { CurrencyCode = "DZD", Name = "Algerian Dinar", CountryCode = "DZ" },
                    new Currency { CurrencyCode = "MAD", Name = "Moroccan Dirham", CountryCode = "MA" },
                    new Currency { CurrencyCode = "KES", Name = "Kenyan Shilling", CountryCode = "KE" },
                    new Currency { CurrencyCode = "LKR", Name = "Sri Lankan Rupee", CountryCode = "LK" },
                    new Currency { CurrencyCode = "CRC", Name = "Costa Rican Colón", CountryCode = "CR" },
                    new Currency { CurrencyCode = "JOD", Name = "Jordanian Dinar", CountryCode = "JO" },
                    new Currency { CurrencyCode = "OMR", Name = "Omani Rial", CountryCode = "OM" },
                    new Currency { CurrencyCode = "UYU", Name = "Uruguayan Peso", CountryCode = "UY" },
                    new Currency { CurrencyCode = "BHD", Name = "Bahraini Dinar", CountryCode = "BH" },
                    new Currency { CurrencyCode = "BOB", Name = "Bolivian Boliviano", CountryCode = "BO" },
                    new Currency { CurrencyCode = "BGN", Name = "Bulgarian Lev", CountryCode = "BG" },
                    new Currency { CurrencyCode = "HRK", Name = "Croatian Kuna", CountryCode = "HR" },
                    new Currency { CurrencyCode = "DOP", Name = "Dominican Peso", CountryCode = "DO" },
                    new Currency { CurrencyCode = "GHS", Name = "Ghanaian Cedi", CountryCode = "GH" },
                    new Currency { CurrencyCode = "GTQ", Name = "Guatemalan Quetzal", CountryCode = "GT" },
                    new Currency { CurrencyCode = "IQD", Name = "Iraqi Dinar", CountryCode = "IQ" },
                    new Currency { CurrencyCode = "JMD", Name = "Jamaican Dollar", CountryCode = "JM" },
                    new Currency { CurrencyCode = "KZT", Name = "Kazakhstani Tenge", CountryCode = "KZ" },
                    new Currency { CurrencyCode = "LBP", Name = "Lebanese Pound", CountryCode = "LB" },
                    new Currency { CurrencyCode = "MUR", Name = "Mauritian Rupee", CountryCode = "MU" },
                    new Currency { CurrencyCode = "MNT", Name = "Mongolian Tugrik", CountryCode = "MN" },
                    new Currency { CurrencyCode = "NAD", Name = "Namibian Dollar", CountryCode = "NA" },
                    new Currency { CurrencyCode = "NPR", Name = "Nepalese Rupee", CountryCode = "NP" },
                    new Currency { CurrencyCode = "NIO", Name = "Nicaraguan Córdoba", CountryCode = "NI" },
                    new Currency { CurrencyCode = "PYG", Name = "Paraguayan Guaraní", CountryCode = "PY" },
                    new Currency { CurrencyCode = "RSD", Name = "Serbian Dinar", CountryCode = "RS" },
                    new Currency { CurrencyCode = "TND", Name = "Tunisian Dinar", CountryCode = "TN" },
                    new Currency { CurrencyCode = "UGX", Name = "Ugandan Shilling", CountryCode = "UG" },
                    new Currency { CurrencyCode = "UZS", Name = "Uzbekistani Som", CountryCode = "UZ" },
                    new Currency { CurrencyCode = "VES", Name = "Venezuelan Bolívar Soberano", CountryCode = "VE" },
                    new Currency { CurrencyCode = "ZMW", Name = "Zambian Kwacha", CountryCode = "ZM" },
                    new Currency { CurrencyCode = "BYN", Name = "Belarusian Ruble", CountryCode = "BY" },
                    new Currency { CurrencyCode = "ISK", Name = "Icelandic Króna", CountryCode = "IS" },
                    new Currency { CurrencyCode = "MDL", Name = "Moldovan Leu", CountryCode = "MD" },
                    new Currency { CurrencyCode = "MKD", Name = "North Macedonian Denar", CountryCode = "MK" },
                    new Currency { CurrencyCode = "TZS", Name = "Tanzanian Shilling", CountryCode = "TZ" },
                    new Currency { CurrencyCode = "ALL", Name = "Albanian Lek", CountryCode = "AL" },
                    new Currency { CurrencyCode = "AMD", Name = "Armenian Dram", CountryCode = "AM" },
                    new Currency { CurrencyCode = "AZN", Name = "Azerbaijani Manat", CountryCode = "AZ" },
                    new Currency { CurrencyCode = "BBD", Name = "Barbadian Dollar", CountryCode = "BB" },
                    new Currency { CurrencyCode = "BMD", Name = "Bermudian Dollar", CountryCode = "BM" },
                    new Currency { CurrencyCode = "BND", Name = "Brunei Dollar", CountryCode = "BN" },
                    new Currency { CurrencyCode = "BSD", Name = "Bahamian Dollar", CountryCode = "BS" },
                    new Currency { CurrencyCode = "BWP", Name = "Botswanan Pula", CountryCode = "BW" },
                    new Currency { CurrencyCode = "BZD", Name = "Belize Dollar", CountryCode = "BZ" },
                    new Currency { CurrencyCode = "FJD", Name = "Fijian Dollar", CountryCode = "FJ" },
                    new Currency { CurrencyCode = "GEL", Name = "Georgian Lari", CountryCode = "GE" },
                    new Currency { CurrencyCode = "HNL", Name = "Honduran Lempira", CountryCode = "HN" },
                    new Currency { CurrencyCode = "HTG", Name = "Haitian Gourde", CountryCode = "HT" },
                    new Currency { CurrencyCode = "KGS", Name = "Kyrgyzstani Som", CountryCode = "KG" },
                    new Currency { CurrencyCode = "KHR", Name = "Cambodian Riel", CountryCode = "KH" },
                    new Currency { CurrencyCode = "LAK", Name = "Lao Kip", CountryCode = "LA" },
                    new Currency { CurrencyCode = "MMK", Name = "Myanmar Kyat", CountryCode = "MM" },
                    new Currency { CurrencyCode = "MVR", Name = "Maldivian Rufiyaa", CountryCode = "MV" },
                    new Currency { CurrencyCode = "PAB", Name = "Panamanian Balboa", CountryCode = "PA" },
                    new Currency { CurrencyCode = "SCR", Name = "Seychellois Rupee", CountryCode = "SC" },
                    new Currency { CurrencyCode = "SVC", Name = "Salvadoran Colón", CountryCode = "SV" },
                    new Currency { CurrencyCode = "SYP", Name = "Syrian Pound", CountryCode = "SY" },
                    new Currency { CurrencyCode = "TTD", Name = "Trinidad and Tobago Dollar", CountryCode = "TT" },
                    new Currency { CurrencyCode = "ANG", Name = "Netherlands Antillean Guilder", CountryCode = "CW" },
                    new Currency { CurrencyCode = "AOA", Name = "Angolan Kwanza", CountryCode = "AO" },
                    new Currency { CurrencyCode = "AWG", Name = "Aruban Florin", CountryCode = "AW" },
                    new Currency { CurrencyCode = "BAM", Name = "Bosnia and Herzegovina Convertible Mark", CountryCode = "BA" },
                    new Currency { CurrencyCode = "BTN", Name = "Bhutanese Ngultrum", CountryCode = "BT" },
                    new Currency { CurrencyCode = "CVE", Name = "Cape Verdean Escudo", CountryCode = "CV" },
                    new Currency { CurrencyCode = "DJF", Name = "Djiboutian Franc", CountryCode = "DJ" },
                    new Currency { CurrencyCode = "ETB", Name = "Ethiopian Birr", CountryCode = "ET" },
                    new Currency { CurrencyCode = "GMD", Name = "Gambian Dalasi", CountryCode = "GM" },
                    new Currency { CurrencyCode = "GNF", Name = "Guinean Franc", CountryCode = "GN" },
                    new Currency { CurrencyCode = "GYD", Name = "Guyanese Dollar", CountryCode = "GY" },
                    new Currency { CurrencyCode = "IRR", Name = "Iranian Rial", CountryCode = "IR" },
                    new Currency { CurrencyCode = "LSL", Name = "Lesotho Loti", CountryCode = "LS" },
                    new Currency { CurrencyCode = "LYD", Name = "Libyan Dinar", CountryCode = "LY" },
                    new Currency { CurrencyCode = "MGA", Name = "Malagasy Ariary", CountryCode = "MG" },
                    new Currency { CurrencyCode = "MOP", Name = "Macanese Pataca", CountryCode = "MO" },
                    new Currency { CurrencyCode = "MRU", Name = "Mauritanian Ouguiya", CountryCode = "MR" },
                    new Currency { CurrencyCode = "MWK", Name = "Malawian Kwacha", CountryCode = "MW" },
                    new Currency { CurrencyCode = "MZN", Name = "Mozambican Metical", CountryCode = "MZ" },
                    new Currency { CurrencyCode = "PGK", Name = "Papua New Guinean Kina", CountryCode = "PG" },
                    new Currency { CurrencyCode = "RWF", Name = "Rwandan Franc", CountryCode = "RW" },
                    new Currency { CurrencyCode = "SBD", Name = "Solomon Islands Dollar", CountryCode = "SB" },
                    new Currency { CurrencyCode = "SDG", Name = "Sudanese Pound", CountryCode = "SD" },
                    new Currency { CurrencyCode = "SLL", Name = "Sierra Leonean Leone", CountryCode = "SL" },
                    new Currency { CurrencyCode = "SRD", Name = "Surinamese Dollar", CountryCode = "SR" },
                    new Currency { CurrencyCode = "STN", Name = "São Tomé and Príncipe Dobra", CountryCode = "ST" },
                    new Currency { CurrencyCode = "SZL", Name = "Swazi Lilangeni", CountryCode = "SZ" },
                    new Currency { CurrencyCode = "TJS", Name = "Tajikistani Somoni", CountryCode = "TJ" },
                    new Currency { CurrencyCode = "TMT", Name = "Turkmenistani Manat", CountryCode = "TM" },
                    new Currency { CurrencyCode = "TOP", Name = "Tongan Paʻanga", CountryCode = "TO" },
                    new Currency { CurrencyCode = "XAF", Name = "Central African CFA Franc", CountryCode = "CM" },
                    new Currency { CurrencyCode = "XCD", Name = "East Caribbean Dollar", CountryCode = "AG" },
                    new Currency { CurrencyCode = "XOF", Name = "West African CFA Franc", CountryCode = "BJ" },
                    new Currency { CurrencyCode = "XPF", Name = "CFP Franc", CountryCode = "PF" },
                    new Currency { CurrencyCode = "YER", Name = "Yemeni Rial", CountryCode = "YE" },
                    new Currency { CurrencyCode = "ZWL", Name = "Zimbabwean Dollar", CountryCode = "ZW" },
                    new Currency { CurrencyCode = "AFN", Name = "Afghan Afghani", CountryCode = "AF" },
                    new Currency { CurrencyCode = "CDF", Name = "Congolese Franc", CountryCode = "CD" },
                    new Currency { CurrencyCode = "CUP", Name = "Cuban Peso", CountryCode = "CU" },
                    new Currency { CurrencyCode = "ERN", Name = "Eritrean Nakfa", CountryCode = "ER" },
                    new Currency { CurrencyCode = "KPW", Name = "North Korean Won", CountryCode = "KP" },
                    new Currency { CurrencyCode = "SSP", Name = "South Sudanese Pound", CountryCode = "SS" },
                    new Currency { CurrencyCode = "VUV", Name = "Vanuatu Vatu", CountryCode = "VU" },
                    new Currency { CurrencyCode = "WST", Name = "Samoan Tala", CountryCode = "WS" },
                    new Currency { CurrencyCode = "SHP", Name = "Saint Helena Pound", CountryCode = "SH" },
                    new Currency { CurrencyCode = "KID", Name = "Kiribati Dollar", CountryCode = "KI" }
            };
                context.Currencies.AddRange(currencies);
                context.SaveChanges();
                Console.WriteLine("Currencies seeded successfully.");
            }
        }
    }
}
