name: Build and deploy ASP.Net Core app to Azure Web App - fliq

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Run Database Migrations
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
          dotnet add Fliq.Infrastructure/Fliq.Infrastructure.csproj package Microsoft.EntityFrameworkCore.Tools
          dotnet restore
          dotnet build --configuration Release
          $workspace = "${{ github.workspace }}"
          $infrastructure_path = Join-Path $workspace "Fliq.Infrastructure\Fliq.Infrastructure.csproj"
          $webapi_path = Join-Path $workspace "Fliq.WebAPI\Fliq.WebAPI.csproj"
          update-database `
            --project $infrastructure_path `
            --startup-project $webapi_path `
            --connection "${{ secrets.AZURE_SQL_CONNECTION_STRING }}" `
            --verbose
        shell: pwsh
        env:
          ASPNETCORE_ENVIRONMENT: Production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fliqapidev'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
