name: Build and deploy ASP.Net Core app to Azure Web App - fliq

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release ConnectVibe.Api/ConnectVibe.Api.csproj

      - name: dotnet publish
        run: dotnet publish ConnectVibe.Api/ConnectVibe.Api.csproj -c Release -o ${{ github.workspace }}/output

      - name: List output directory contents
        run: dir ${{ github.workspace }}/output

      - name: Zip published output
        run: Compress-Archive -Path ${{ github.workspace }}/output/* -DestinationPath ${{ github.workspace }}/output/output.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/output/output.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Unzip artifact
        run: Expand-Archive -Path ./.net-app/output.zip -DestinationPath ${{ github.workspace }}/unzipped-output

      - name: List unzipped directory contents
        run: dir ${{ github.workspace }}/unzipped-output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C403734509FF4ACC822CFD4C485B6E31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8CF8C78EA03C49879FD0A931AED1B50D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D9794605284B4B8099F189410FC82DA2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fliq'
          slot-name: 'Production'
          package: ${{ github.workspace }}/unzipped-output
